name: Update

on:
  schedule:
    - cron: "0 23 * * *"
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Configure Git
        run: |
          git config user.name github-actions[bot]
          git config user.email github-actions[bot]@users.noreply.github.com

      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - uses: actions/cache@v4
        with:
          key: deno-${{ hashFiles('deno.lock', '.github/workflows/**') }}
          restore-keys: deno-
          path: |
            /home/runner/.cache/deno

      - name: Cache
        run: deno task cache

      - name: Update and Commit
        run: deno task update:commit

      - name: Check changes
        id: changes
        uses: andstor/file-existence-action@v3
        with:
          files: ../title.txt, ../body.md

      - name: Read title.txt
        id: title
        if: steps.changes.outputs.files_exists == 'true'
        uses: juliangruber/read-file-action@v1
        with:
          path: ../title.txt

      - name: Read body.md
        id: body
        if: steps.changes.outputs.files_exists == 'true'
        uses: juliangruber/read-file-action@v1
        with:
          path: ../body.md

      - name: Create Pull Request
        if: steps.changes.outputs.files_exists == 'true'
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GH_TOKEN }}
          author: github-actions[bot] <github-actions[bot]@users.noreply.github.com>
          branch: ${{ inputs.head-branch }}
          title: ${{ steps.title.outputs.content }}
          body: ${{ steps.body.outputs.content }}
          labels: dependencies
          delete-branch: true
